version: "3.8"

volumes:
  dbdata:

services:
  app:
    build: ./
    volumes:
      - ./www:/var/www:z
    ports:
      - 3000:80
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/public_html
  db:
    image: mariadb:10.5.20
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3406:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
  pma:
    image: phpmyadmin
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_PORT: 3406
      UPLOAD_LIMIT: 30M
    ports:
      - 3001:80
    depends_on:
      - db
  css:
    build:
      context: ./
      dockerfile: ./DockerfileCSS
    command: npm start
    tty: true
    volumes:
      - .:/node:z
