version: "3.8"

volumes:
  dbdata:

services:
  app:
    build: ./
    volumes:
      - ./public_html:/var/www/html:z
      - ./src:/var/www/src:z
    ports:
      - 3000:80
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
  pma:
    image: phpmyadmin
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - 3001:80
    depends_on:
      - db